name: esBuild
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docker/**'
    - 'docs/**'
    - 'notebooks/**'
    - '.github/markdown.yml'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
    - master
    paths-ignore:
    - 'docker/**'
    - 'docs/**'
    - 'notebooks/**'
    - '.github/markdown.yml'

jobs:
  universal:
    name: Build with esBuild
    if: ${{ github.event_name == 'push' || github.event.pull_request.draft == false }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Installing Pipcook
      run: |
        yarn
    - name: Building Pipcook
      run: |
        yarn dev-build
    - name: Running unit tests
      run: |
        ulimit -c unlimited
        echo "$PWD/core/%e-%p-%t.core" | sudo tee /proc/sys/kernel/core_pattern
        mkdir -p core
        yarn init-dev
        yarn test
    - name: Uploading coredump
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: build-core-dump
        path: |
          core/
          packages/boa/build/
    - name: Printing the stacktrace from coredump
      if: ${{ failure() }}
      run: |
        apt-get install gdb
        gdb -h
        gdb -ex=bt -ex=quit -c core/*.core
